# -*- coding: utf-8 -*-
"""Avi_Lotto_Ultra_Ensemble.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pL1e343vOXqzKljVJmql626Gx09zxx61
"""

# ================= Avi Ultra Lotto Ensemble =================
# תא יחיד: משיכת נתונים אמיתית, חישוב מלא, Backtesting, Monte Carlo, פלט טפסים + CSV

import requests, re, math, os
from datetime import datetime
from collections import Counter, defaultdict
from itertools import combinations
import numpy as np
import pandas as pd
from bs4 import BeautifulSoup

# ---------- פרמטרים ----------
MIN_DRAWS = 250
NUM_MAIN  = 6
MAX_MAIN  = 37
EXTRA_MIN, EXTRA_MAX = 1, 7
NUM_TICKETS = 12
SEED = 987654321
ANTI_DUP_OVERLAP = 5

# משקלים
W_FREQ, W_RECENCY, W_TREND, W_BALANCE = 1.0, 0.9, 0.55, 0.2
W_PAIR_SYNERGY, W_SPREAD, W_RANGE_MIX, W_ODD_EVEN, W_LAST_DIGIT = 0.35,0.25,0.2,0.1,0.05
W_MONTECARLO = 0.6
MC_DRAWS = 8000
REWARD = { (6,1):100,(6,0):60,(5,1):20,(5,0):10,(4,1):5,(4,0):2,(3,1):1,(3,0):0.3,(2,1):0.15,(1,1):0.08,(0,1):0.05 }

rng = np.random.default_rng(SEED)
session = requests.Session()
session.headers.update({"User-Agent":"Mozilla/5.0"})